const chat=document.querySelector('#chat'),promptEl=document.querySelector('#prompt'),form=document.querySelector('#composer'),files=document.querySelector('#files'),attachments=document.querySelector('#attachments');
const welcome=()=>chat.innerHTML='<div class="welcome"><div class="nova">N</div><h2>What can I help with?</h2><p>Ask a TBRN process question, review claim evidence, assess costs or draft correspondence.</p><div class="suggestions"><button>What evidence should support a third-party recovery?</button><button>Help me assess a contractor estimate</button><button>Draft a request for an itemised breakdown</button></div></div>';
function add(role,text,sources=[]){const row=document.createElement('div');row.className='message '+role;const b=document.createElement('div');b.className='bubble';b.textContent=text;if(sources.length){const s=document.createElement('div');s.className='source';s.textContent='Sources: '+sources.join(', ');b.appendChild(s)}row.appendChild(b);chat.appendChild(row);chat.scrollTop=chat.scrollHeight}
async function ask(text){add('user',text);promptEl.value='';const pending='Thinking…';add('assistant',pending);const bubble=chat.lastChild.querySelector('.bubble');try{const r=await fetch('/api/tbrn-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});if(!r.ok)throw new Error();const data=await r.json();bubble.textContent=data.answer||'No answer returned.';if(data.sources?.length){const s=document.createElement('div');s.className='source';s.textContent='Sources: '+data.sources.join(', ');bubble.appendChild(s)}}catch{bubble.textContent='Nova’s secure AI backend is not connected in this standalone interface yet. The front-end test build is working; the next step is connecting the protected API and TBRN knowledge index.'}files.value='';attachments.textContent=''}
form.addEventListener('submit',e=>{e.preventDefault();const t=promptEl.value.trim();if(t)ask(t)});
promptEl.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});
files.addEventListener('change',()=>attachments.textContent=[...files.files].map(f=>f.name).join(' • '));
document.addEventListener('click',e=>{if(e.target.matches('.suggestions button')){promptEl.value=e.target.textContent;form.requestSubmit()}if(e.target.matches('nav button')){promptEl.value=e.target.dataset.prompt;promptEl.focus()}});
document.querySelector('#newChat').onclick=welcome;
const dlg=document.querySelector('#knowledge');document.querySelector('#knowledgeBtn').onclick=()=>dlg.showModal();dlg.querySelector('.close').onclick=()=>dlg.close();
fetch('/api/health').then(r=>r.ok?r.json():Promise.reject()).then(()=>document.querySelector('#backendStatus').textContent='Connected').catch(()=>document.querySelector('#backendStatus').textContent='Not connected');